options {
  directory "/var/cache/bind";
  listen-on { 172.31.0.11; };
  listen-on-v6 { none; };

  allow-query { any; };
  recursion no;
  allow-transfer { none; };
  minimal-responses yes;

  rate-limit {
    responses-per-second 20;
    window 5;
    slip 2;
  };

  key-directory "/etc/bind/keys";
};

logging {
  channel default_log {
    file "/var/log/bind/named.log" versions 3 size 5m;
    severity info;
    print-time yes;
    print-severity yes;
    print-category yes;
  };

  category default { default_log; };
  category dnssec { default_log; };
  category security { default_log; };
  category rate-limit { default_log; };
};

zone "example.test" {
  type primary;
  file "/etc/bind/zones/db.example.test.signed";
};
