server:
  username: "_unbound"
  directory: "/opt/unbound/etc/unbound"
  chroot: ""
  logfile: "/var/log/unbound/unbound.log"
  verbosity: 1
  val-log-level: 1
  log-servfail: no
  log-queries: no
  log-replies: no
  log-local-actions: no
  log-tag-queryreply: no
  ede: yes

  module-config: "validator iterator"

  interface: 0.0.0.0@53
  port: 53
  tls-port: 853
  tls-service-key: "/opt/unbound/etc/unbound/tls/server.key"
  tls-service-pem: "/opt/unbound/etc/unbound/tls/server.pem"

  do-ip4: yes
  do-udp: yes
  do-tcp: yes

  access-control: 127.0.0.0/8 allow
  access-control: 172.32.0.0/24 allow
  access-control: 172.30.0.0/24 allow
  access-control: 172.33.0.0/24 refuse
  
  # Override Unbound's built-in RFC 2606 .test local-zone.
  local-zone: "test." nodefault

  qname-minimisation: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  aggressive-nsec: yes
  minimal-responses: yes
  prefetch: yes

  trust-anchor-file: "/opt/unbound/etc/unbound/anchors/test.key"
  root-hints: "/opt/unbound/etc/unbound/root.hints"

stub-zone:
  name: "test."
  stub-addr: 172.31.0.10

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  control-port: 8953
  server-key-file: "/opt/unbound/etc/unbound/unbound_server.key"
  server-cert-file: "/opt/unbound/etc/unbound/unbound_server.pem"
  control-key-file: "/opt/unbound/etc/unbound/unbound_control.key"
  control-cert-file: "/opt/unbound/etc/unbound/unbound_control.pem"
