server:
  username: "unbound"
  directory: "/opt/unbound/etc/unbound"
  logfile: "/var/log/unbound/unbound.log"
  verbosity: 1

  interface: 0.0.0.0
  port: 53

  do-ip4: yes
  do-udp: yes
  do-tcp: yes

  access-control: 127.0.0.0/8 allow
  access-control: 172.32.0.0/24 allow
  access-control: 172.30.0.0/24 allow
  access-control: 172.33.0.0/24 refuse

  qname-minimisation: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  minimal-responses: yes
  prefetch: yes

  auto-trust-anchor-file: "/opt/unbound/etc/unbound/root.key"
  root-hints: "/opt/unbound/etc/unbound/root.hints"

stub-zone:
  name: "example.test"
  stub-addr: 172.31.0.10
