server:
  username: "_unbound"
  directory: "/opt/unbound/etc/unbound"
  chroot: ""
  logfile: "/var/log/unbound/unbound.log"
  verbosity: 1
  log-servfail: no
  log-queries: no
  log-replies: no
  log-local-actions: no
  log-tag-queryreply: no

  module-config: "iterator"

  interface: 0.0.0.0@53
  port: 53
  tls-port: 853
  tls-service-key: "/opt/unbound/etc/unbound/tls/server.key"
  tls-service-pem: "/opt/unbound/etc/unbound/tls/server.pem"

  do-ip4: yes
  do-udp: yes
  do-tcp: yes

  access-control: 127.0.0.0/8 allow
  access-control: 172.32.0.0/24 allow
  access-control: 172.30.0.0/24 allow
  access-control: 172.33.0.0/24 refuse

  # Allow RFC 2606 .test to resolve via stub-zone.
  local-zone: "test." transparent

  qname-minimisation: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  minimal-responses: yes
  prefetch: yes

  root-hints: "/opt/unbound/etc/unbound/root.hints"

stub-zone:
  name: "test."
  stub-addr: 172.31.0.10
